- name: Install openvpn
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - openvpn
    - openssl
    - iptables
    - bridge-utils

- name: Install LDAP plugin
  package:
   name: openvpn-auth-ldap
   state: present
  when: openvpn_ldap is defined

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: yes
